In [27]:
#imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier

In [28]:
#reading dataset
df = pd.read_csv('loan_approval_dataset.csv')
df.head()

   loan_id   no_of_dependents  ...  bank_asset_value  loan_status
0        1                  2  ...           8000000     Approved
1        2                  0  ...           3300000     Rejected
2        3                  3  ...          12800000     Rejected
3        4                  3  ...           7900000     Rejected
4        5                  5  ...           5000000     Rejected

[5 rows x 13 columns]

In [29]:
#dropping id
df.drop('loan_id', axis=1, inplace=True)
df.head()

   no_of_dependents      education  ... bank_asset_value  loan_status
0                 2       Graduate  ...          8000000     Approved
1                 0   Not Graduate  ...          3300000     Rejected
2                 3       Graduate  ...         12800000     Rejected
3                 3       Graduate  ...          7900000     Rejected
4                 5   Not Graduate  ...          5000000     Rejected

[5 rows x 12 columns]

In [30]:
#checking null values to handle them
print(df.isnull().sum())

no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [31]:
#checking for categorical values to encode them
categorical_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_cols.tolist())
#had to strip strings en order for the smote to work as without stripping them some values were no encoded
df.columns = df.columns.str.strip()

Categorical columns: [' education', ' self_employed', ' loan_status']

In [32]:
#encoding
encode = ['education', 'self_employed', 'loan_status']
le = LabelEncoder()

for col in encode:
    if col in df.columns:
        df[col] = le.fit_transform(df[col])

In [33]:
#splitting & training data
X = df.drop(['loan_status'], axis=1)
y = df['loan_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
#handling class imbalance using SMOTE
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [37]:
#logistic regression
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_res, y_train_res)
y_pred = log_reg.predict(X_test)

In [36]:
#decision tree
m_dt = DecisionTreeClassifier(random_state=42)
m_dt.fit(X_train, y_train)
dt_preds = m_dt.predict(X_test)

In [38]:
#evaluation with metrics
print("Logistic Regression Classification Report:")
print(classification_report(y_test, y_pred))
print("\nDecision Tree Classification Report:")
print(classification_report(y_test, dt_preds))

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.85      0.83       536
           1       0.72      0.68      0.70       318

    accuracy                           0.78       854
   macro avg       0.77      0.76      0.77       854
weighted avg       0.78      0.78      0.78       854


Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       536
           1       0.97      0.97      0.97       318

    accuracy                           0.98       854
   macro avg       0.98      0.98      0.98       854
weighted avg       0.98      0.98      0.98       854